import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, SafeAreaView, TouchableOpacity, TextInput, ActivityIndicator, Alert, KeyboardAvoidingView, Platform } from 'react-native';
import { ArrowLeft, Sword } from 'lucide-react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useBattleStore } from '../store/battleStore';
import useAuthStore from '../store/authStore';

const JoinBattleScreen = ({ navigation }) => {
  const { user } = useAuthStore();
  const { joinRoom, status, roomCode, error } = useBattleStore();
  const [codeInput, setCodeInput] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (status === 'lobby' && roomCode) {
      setLoading(false);
      navigation.replace('Lobby', { roomCode });
    }
    if (error) {
      setLoading(false);
      Alert.alert('Error', error);
      useBattleStore.setState({ error: null });
    }
  }, [status, roomCode, error]);

  const handleJoin = () => {
    if (codeInput.length < 6) {
      Alert.alert('Invalid Code', 'Please enter a complete 6-character room code.');
      return;
    }
    
    setLoading(true);
    const userId = user?.id || 'temp_player';
    const userName = user?.email?.split('@')[0] || 'Player';
    
    joinRoom(codeInput.toUpperCase(), userId, userName);
  };

  return (
    <SafeAreaView style={styles.container}>
      <LinearGradient
        colors={['#1E1B4B', '#2E0854']}
        style={StyleSheet.absoluteFillObject}
      />
      
      <KeyboardAvoidingView 
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={{ flex: 1 }}
      >
        <View style={styles.header}>
          <TouchableOpacity style={styles.backButton} onPress={() => navigation.goBack()}>
            <ArrowLeft size={24} color="#FFF" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Join Arena</Text>
          <View style={{ width: 40 }} />
        </View>

        <View style={styles.content}>
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Enter Battle Code</Text>
            <Text style={styles.cardDesc}>Enter the 6-digit room code generated by the host to join their live MCQ duel.</Text>
            
            <TextInput 
              style={styles.input}
              placeholder="ENTER CODE"
              placeholderTextColor="rgba(255,255,255,0.2)"
              value={codeInput}
              onChangeText={(text) => setCodeInput(text.toUpperCase())}
              maxLength={6}
              autoCapitalize="characters"
              autoCorrect={false}
              autoFocus={true}
              keyboardType="default"
            />

            <TouchableOpacity 
              style={[styles.joinButton, codeInput.length < 6 && styles.disabledButton]}
              onPress={handleJoin}
              disabled={codeInput.length < 6 || loading}
              activeOpacity={0.8}
            >
              {loading ? (
                <ActivityIndicator color="#FFF" />
              ) : (
                <>
                  <Sword size={20} color="#FFF" />
                  <Text style={styles.joinText}>Enter Arena</Text>
                </>
              )}
            </TouchableOpacity>
          </View>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    paddingHorizontal: 20, 
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)'
  },
  backButton: { 
    width: 40, 
    height: 40, 
    borderRadius: 20, 
    backgroundColor: 'rgba(255,255,255,0.1)', 
    justifyContent: 'center', 
    alignItems: 'center' 
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#FFF' },
  content: { flex: 1, justifyContent: 'center', padding: 24 },
  card: { 
    backgroundColor: 'rgba(255, 255, 255, 0.05)', 
    borderWidth: 1, 
    borderColor: 'rgba(255, 255, 255, 0.1)', 
    borderRadius: 28, 
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 5
  },
  cardTitle: { fontSize: 22, fontWeight: 'bold', color: '#FFF', marginBottom: 10 },
  cardDesc: { fontSize: 13, color: '#A5B4FC', textAlign: 'center', marginBottom: 30, lineHeight: 18 },
  input: { 
    backgroundColor: 'rgba(0,0,0,0.3)', 
    width: '100%',
    height: 64, 
    borderRadius: 16, 
    paddingHorizontal: 15, 
    fontSize: 24, 
    fontWeight: 'bold', 
    color: '#FFF', 
    textAlign: 'center', 
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    letterSpacing: 4
  },
  joinButton: { 
    backgroundColor: '#6366F1', 
    width: '100%',
    height: 56, 
    borderRadius: 16, 
    flexDirection: 'row', 
    justifyContent: 'center', 
    alignItems: 'center',
    shadowColor: '#6366F1',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 3
  },
  joinText: { color: '#FFF', fontSize: 16, fontWeight: 'bold', marginLeft: 10 },
  disabledButton: { backgroundColor: 'rgba(99, 102, 241, 0.4)', shadowOpacity: 0 }
});

export default JoinBattleScreen;
